<!-- Replace below with the title of your project -->
### Is Solar Energy A Political Issue


<!-- Replace below with your last and first name -->
#### Tuckman, Jonah


<!-- Enter the code required to load your data in the space below. The data will be loaded but the line of code won't show up in your write up (echo=FALSE) in order to save space-->
```{r echo=FALSE}
setwd('/Users/JonahTuckman/Desktop/Spring2019/Statistics/Statistics-MATH-240/Final Project')
statsData <- read.csv('State RE Generation-Table 1.csv') ## Original dataset with many extra energy types
neededCols <- c("State","Solar") ## Focusing on states and Solar output
statsData <- statsData[neededCols] ## Taking only those columns stated above
## Merging voting history 
Voting <- read.csv("Voting.csv")
statsData <- merge(statsData, Voting, by="State")
write.csv(statsData, "SolarData.csv") ## Writing this new file


statsData <- read.csv("SolarData.csv") ## Reading this new file
statsData['X'] <- NULL ## Deleted unneeded column

replaceCommas<-function(X){
  X<-as.numeric(gsub("\\,", "", X))
}

statsData$Solar <- replaceCommas(statsData$Solar)
statsData <- transform(statsData, Republican = ifelse(statsData$Voting == 'R', 1,0))

### Remove NA values
statsData$Republican[is.na(statsData$Republican)] <- 0
statsData$Solar[is.na(statsData$Solar)] <- 0

# Solar positive column
statsData <- transform(statsData, SolarPositive = ifelse(statsData$Solar > 0, 1, 0))

# New set of solely boolean data
keepers <- c("State", "Republican", "SolarPositive")
BooleanData <- statsData[keepers]
BooleanData[is.na(BooleanData)] <- 0



### Dataset splits based on political affiliation
RepData <- subset(statsData, statsData$Voting == 'R')
DemData <- subset(statsData, statsData$Voting == 'D')

```

<!-- In the remainder of the document, add R code chunks as needed -->

### Introduction:

My research question is whether or not the solar output of each state can be dictated by political afiliation. This question pivoted from the original based on a poor representation of overal data. My initial question that I hoped to explore was whether headquarter location of top 10 (in valuation) american oil companies affected state wide solar output. The hiccup I ran into when exploring this was that over 70% of these companies had their headquarters in Texas. This lead to a poor dataset as there was a low representation in other states. 
After I realized this I pivoted my question to explore whether solar output state wide can see a correlation between positive output and political voting patterns. This is an interesting question because the idea of solar energy is one that is globaly impactful for all states and people, independent of political affiliation. 
Positive aspects include limited reliance on oil (and thus foreign policy implications as the US needs to send less soldiers to wars fought over dictating oil rich regions), climate change reduction (the fossil fuel emissions would be limited if cars, trains, planes and more were running off of solar power rather than currently harmful tendencies), fiscal advantages (government stipends for those who opt into a switch into renewable energy) and many more. I found interest in this question after deciding to work for a company over the summer who works towards using Artificial Inteligence to advance the output and profitability of solar fields. Once understanding this aspect of solar energy I began to wonder whether the aspects still holding us back could be political. 



### Data:

Cohesive write-up of the data section from your proposal. Review instructions for proposal.

https://catalog.data.gov/dataset/energy-generation-by-state-and-technology-2009/resource/bb0da868-f498-4c47-b61f-da217897198f

My initial data was from a 2009 study of Energy Generation by Source and State alongside the results from the 2008 general election by state. 
I initially sliced this Energy Generation csv in order to solely include State and Solar output. This dataset includes all types of energy output (Coal, petrolium, solar, wind, etc) but I decided to limit this study to solely solar output. A thought I had for a later extension of this project would be to broaden the exploration and create a boolean variable for all renewable energy output. This would encompass states who have a positive renewable output that does not include solar, thus making our exploration more accurate. 
Once I had a set of States and Solar output, I pulled data of voting records and merged this into the current dataset by state name. Now my data includes State, Voting History, and Solar output. 
From here I did a variety of things to be used later including splitting into seperate Democratic and Republican sets, adding a boolean variable of Solar Positivity to the original set and adding a boolean variable of Republican to the original set. 


### Exploratory data analysis:

Perform relevant descriptive statistics, including summary statistics and visualization of the data. Also address what the exploratory data analysis suggests about your research question.

### Inference:

Use theoretical and/or simulation methods to perform a hypothesis test, and also construct a confidence interval. If your data fails some conditions and you cannot use a theoretical method, then you should use simulation. It is your responsibility to figure out the appropriate methodology, and apply all methods that are appropriate.

Don't forget to state hypotheses clearly and check conditions...

### Conclusion:

Write a brief summary of your findings without repeating your statements from earlier. Also include a discussion of what you have learned about your research question and the data you collected. You should also acknowledge limitations of your study and include ideas for possible future research.

